######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 1 11:06:24 2008
######################################################################
CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
SOURCES += qttest.cpp tstlib/tstlib.cpp
HEADERS += tstlib/tstlib.h
INCLUDEPATH += ./tstlib
DEFINES += WIN32 Q_OS_WIN32
