#!/bin/zsh

BASEDIR=`dirname $0`

if [[ `uname` =~ "CYGWIN*" ]]; then
    echo Cygwin detected
    cd $BASEDIR
    ./vscope.exe
else
    echo No Cygwin detected - Assuming Linux
    #QT_AUTO_SCREEN_SCALE_FACTOR=1
    QT_SCALE_FACTOR=2.25 $BASEDIR/build/vscope $*
fi
