#!/bin/zsh

BASEDIR=`dirname $0`

if [[ `uname` =~ "CYGWIN*" ]]; then
    echo Cygwin detected
    cd $BASEDIR
    ./vscope.exe
else
    echo No Cygwin detected - Assuming Linux
    $BASEDIR/build/vscope
fi
