// enums.h - created from 'enums.xml' by './enum2c.pl'
// Created: Tue Jul 17 10:18:47 PDT 2012 on leech

// DO NOT EDIT THIS FILE. CHANGES WILL BE LOST.
// (Edit 'enums.xml' instead, then rerun './enum2c.pl'.)

#ifndef ENUMS_H
#define ENUMS_H

#define ENUMS_VERSION 20120717

enum PULSETYPE {
  PT_TTL = 0,
  PT_Square = 1,
  PT_Biphasic = 2,
  PT_Ramp = 3,
};

enum SHOWROIS {
  SR_Hidden = 0,
  SR_Centers = 1,
  SR_Outlines = 2,
  SR_IDs = 3,
  SR_Full = 4,
};

enum REFTYPE {
  RT_Analog = 0,
  RT_Digital = 1,
  RT_Frequency = 2,
};

enum DEBLEACH {
  DB_None = 0,
  DB_Linear = 1,
  DB_Quadratic = 2,
  DB_Exponential = 3,
};


#endif
