// xmlenums.h - created from 'config.xml' by './xml2include.pl'
// Created: Wed Sep 17 10:03:00 PDT 2008 on blueboy

// DO NOT EDIT THIS FILE. CHANGES WILL BE LOST.
// (Edit 'config.xml' instead, then rerun './xml2include.pl'.)

#ifndef XMLENUMS_H
#define XMLENUMS_H

#define VERSION_MAJOR 20080917
#define VERSION_MINOR 0

#define AICHAN_ME1_10Vm   0
#define AICHAN_ME2_Vm     1
#define AICHAN_ME1_I      2
#define AICHAN_ME2_I      3
#define AICHAN_StimMon0   4
#define AICHAN_StimMon1   5
#define AICHAN_60HzRef    7
#define AICHAN_ExtVA1     8
#define AICHAN_ExtVA2     9
#define AICHAN_ExtVA3    10
#define AICHAN_ExtVA4    11
#define AICHAN_ExtVB1    12
#define AICHAN_ExtVB2    13
#define AICHAN_ExtVB3    14
#define AICHAN_ExtVB4    15

#define PULSETYPE_TTL        0
#define PULSETYPE_Square     1
#define PULSETYPE_Biphasic   2
#define PULSETYPE_Ramp       3

#define STIMCHS_AO0   0
#define STIMCHS_AO1   1
#define STIMCHS_AO2   2
#define STIMCHS_AO3   3
#define STIMCHS_DO0   4
#define STIMCHS_DO1   5
#define STIMCHS_DO2   6
#define STIMCHS_DO3   7

#define BIN_1x1   1
#define BIN_1x2   2
#define BIN_1x3   3
#define BIN_1x4   4
#define BIN_2x2   5
#define BIN_3x3   6
#define BIN_4x4   7

#define REGION_512x512   1
#define REGION_384x384   2
#define REGION_256x256   3


#endif
