// pvp_Class0.h - generated by pvcam2param.pl. Do not Edit.

  bool availDdInfoLength() /*throw(pvpException)*/;
  pvpAccess accessDdInfoLength() /*throw(pvpException)*/;
  int16_t getDdInfoLength() /*throw(pvpException)*/;
  int16_t minDdInfoLength() /*throw(pvpException)*/;
  int16_t maxDdInfoLength() /*throw(pvpException)*/;
  int16_t defaultDdInfoLength() /*throw(pvpException)*/;
  int16_t stepDdInfoLength() /*throw(pvpException)*/;
  int countDdInfoLength() /*throw(pvpException)*/;
  void setDdInfoLength(int16_t) /*throw(pvpException)*/;
  void reportDdInfoLength() /*throw(pvpException)*/;

  bool availDdVersion() /*throw(pvpException)*/;
  pvpAccess accessDdVersion() /*throw(pvpException)*/;
  uint16_t getDdVersion() /*throw(pvpException)*/;
  uint16_t minDdVersion() /*throw(pvpException)*/;
  uint16_t maxDdVersion() /*throw(pvpException)*/;
  uint16_t defaultDdVersion() /*throw(pvpException)*/;
  uint16_t stepDdVersion() /*throw(pvpException)*/;
  int countDdVersion() /*throw(pvpException)*/;
  void setDdVersion(uint16_t) /*throw(pvpException)*/;
  void reportDdVersion() /*throw(pvpException)*/;

  bool availDdRetries() /*throw(pvpException)*/;
  pvpAccess accessDdRetries() /*throw(pvpException)*/;
  uint16_t getDdRetries() /*throw(pvpException)*/;
  uint16_t minDdRetries() /*throw(pvpException)*/;
  uint16_t maxDdRetries() /*throw(pvpException)*/;
  uint16_t defaultDdRetries() /*throw(pvpException)*/;
  uint16_t stepDdRetries() /*throw(pvpException)*/;
  int countDdRetries() /*throw(pvpException)*/;
  void setDdRetries(uint16_t) /*throw(pvpException)*/;
  void reportDdRetries() /*throw(pvpException)*/;

  bool availDdTimeout() /*throw(pvpException)*/;
  pvpAccess accessDdTimeout() /*throw(pvpException)*/;
  uint16_t getDdTimeout() /*throw(pvpException)*/;
  uint16_t minDdTimeout() /*throw(pvpException)*/;
  uint16_t maxDdTimeout() /*throw(pvpException)*/;
  uint16_t defaultDdTimeout() /*throw(pvpException)*/;
  uint16_t stepDdTimeout() /*throw(pvpException)*/;
  int countDdTimeout() /*throw(pvpException)*/;
  void setDdTimeout(uint16_t) /*throw(pvpException)*/;
  void reportDdTimeout() /*throw(pvpException)*/;

  bool availDdInfo() /*throw(pvpException)*/;
  pvpAccess accessDdInfo() /*throw(pvpException)*/;
  QString getDdInfo() /*throw(pvpException)*/;
  QString minDdInfo() /*throw(pvpException)*/;
  QString maxDdInfo() /*throw(pvpException)*/;
  QString defaultDdInfo() /*throw(pvpException)*/;
  QString stepDdInfo() /*throw(pvpException)*/;
  int countDdInfo() /*throw(pvpException)*/;
  void setDdInfo(QString) /*throw(pvpException)*/;
  void reportDdInfo() /*throw(pvpException)*/;

  void reportClass0() /*throw(pvpException)*/;
