######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 10 20:14:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gstest.C mygv.C
HEADERS += mygv.H