#!/bin/zsh

for DIR in base gfx gui pvp test vsdscope xml; do
  for FILE in $DIR/*.h $DIR/*.cpp; do
    perl -pe 's/float/double/g;' <$FILE > tmp && mv tmp $FILE
  done
done

for DIR in xml; do
  for FILE in $DIR/*.h $DIR/*.cpp; do
    perl -pe 's/Float/Double/g;' <$FILE > tmp && mv tmp $FILE
  done
done
