#!/bin/sh

OUT=$1
TMP=version.tmp
rm -f $TMP

if [ -d ../.bzr/repository ] && [ -d ../.bzr/checkout ]; then
    # We have bazaar
    if [ -f $OUT ] && [ $OUT -nt ../.bzr/repository ] && [ $OUT -nt ../.bzr/checkout ] && [ $OUT -nt $0 ]; then
	# Do nothing
	true
    else
	if bzr version-info > $TMP; then
	    vDATE=`grep '^date:' $TMP | cut -c7-`
	    vREVNO=`grep '^revno:' $TMP | cut -c8-`
	    vBRANCH=`grep '^branch-nick:' $TMP | cut -c14-`
	    vBUILDDATE=`grep '^build-date:' $TMP | cut -c13-`
	    vYEAR=`grep '^date:' $TMP | cut -c7-10`
	else
	    vDATE="?"
	    vREVNO="?"
	    vBRANCH="?"
	    vBUILDDATE=`date '+%Y-%m-%d %H:%M:%S %z' `
	    vYEAR=`date '+%Y'`
	fi
    fi
else
    # We do not have bazaar
    if [ -f $OUT ]; then
	# Do nothing
	true
    else
	vDATE="?"
	vREVNO="?"
	vBRANCH="?"
	vBUILDDATE=`date '+%Y-%m-%d %H:%M:%S %z' `
	vYEAR=`date '+%Y'`
    fi
fi

echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > $OUT
echo '<!DOCTYPE vsdscopeVersion>' >> $OUT
echo '<version ' >> $OUT
echo " branch='$vBRANCH'" >> $OUT
echo " rev='$vREVNO'" >> $OUT
echo " date='$vDATE'" >> $OUT
echo " builddate='$vBUILDDATE'" >> $OUT
echo " year='$vYEAR'" >> $OUT
echo ' />' >> $OUT
