#!/bin/sh

OUT=$1
BASE=$2

TMP=version.tmp
rm -f $TMP

if bzr log -r. --show-ids > $TMP; then
    vDATE=`grep '^timestamp:' $TMP | cut -c16-`
    vREVNO=`grep '^revno:' $TMP | cut -c8-`
    [[ -z `bzr status` ]] || vREVNO=$vREVNO"+"
    vBRANCH=`grep '^branch nick:' $TMP | cut -c14-`
    vYEAR=`grep '^timestamp:' $TMP | cut -c16-19`
    if [[ `uname` == CYGWIN* ]]; then
	EXENAME=vscope.exe
    else
	EXENAME=vscope.bin
    fi
    vBUILDDATE=`ls -l --time-style='+%Y-%m-%d %H:%M:%S %z' $EXENAME |cut -d' ' -f6-8`
else    
    echo No bazaar
    [ -f $OUT ] && exit 0
    vDATE="?"
    vREVNO="?"
    vBRANCH="?"
    vBUILDDATE=`date '+%Y-%m-%d %H:%M:%S %z' `
    vYEAR=`date '+%Y'`
fi


echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > $OUT
echo '<!DOCTYPE vsdscopeVersion>' >> $OUT
echo '<version ' >> $OUT
echo " branch='$vBRANCH'" >> $OUT
echo " rev='$vREVNO'" >> $OUT
echo " date='$vDATE'" >> $OUT
echo " builddate='$vBUILDDATE'" >> $OUT
echo " year='$vYEAR'" >> $OUT
echo ' />' >> $OUT
