// enums.h - created from 'enums.xml' by 'enums2c.pl'
// Created: Fri Aug 10 21:44:36 EDT 2012 on aspire

// DO NOT EDIT THIS FILE. CHANGES WILL BE LOST.
// (Edit 'enums.xml' instead, then rerun 'enums2c.pl'.)

#ifndef ENUMS_H
#define ENUMS_H

#define ENUMS_VERSION 20120717

enum PULSETYPE {
  PT_TTL = 0,
  PT_Square = 1,
  PT_Biphasic = 2,
  PT_Ramp = 3,
};

enum SHOWROIS {
  SR_Hidden = 0,
  SR_Centers = 1,
  SR_Outlines = 2,
  SR_IDs = 3,
  SR_Full = 4,
};

enum REFTYPE {
  RT_Analog = 0,
  RT_Digital = 1,
  RT_Frequency = 2,
};

enum DEBLEACH {
  DB_None = 0,
  DB_Linear = 1,
  DB_Quadratic = 2,
};

enum VISUALTYPE {
  VT_Label = 0,
  VT_PageOpen = 1,
  VT_VarOpen = 2,
  VT_VarValue = 3,
  VT_BooleanVar = 4,
  VT_PanelOpen = 5,
  VT_Action = 6,
  VT_Grouped = 7,
  VT_ArrayCtrl = 8,
};

enum CAMERAS {
  CAM_self = -1,
  CAM_none = -2,
};

enum AICHAN {
  AICHAN_off = -1,
};

enum AOCHAN {
};

enum DIGILINES {
};

enum SHOWWHAT {
  SW_EphysInt = 0,
  SW_EphysExt = 1,
  SW_Stimuli = 2,
  SW_VSDTraces = 3,
  SW_Coherence = 4,
  SW_VideoMon = 5,
  SW_CohGraph = 6,
  SW_Welcome = -1,
};

enum STIMCHS {
};

enum CURRENTCAMERAS {
};


#endif
