#!/bin/sh

SUBDIRS="acq  base  daq  gfx  gui  math  pvp  toplevel   video  xml"

cd `dirname $0`
cd ../src

echo "# Automatically generated by updatesources.sh" > vscope.pri
echo "" >> vscope.pri

for DIR in $SUBDIRS; do
    echo "HEADERS += \\" >> vscope.pri
    find $DIR -maxdepth 1 -name \*.h -exec echo "    " '{}' " \\" ';' | sort >> vscope.pri
    echo "" >> vscope.pri

    echo "SOURCES += \\" >> vscope.pri
    find $DIR -maxdepth 1 -name \*.cpp -exec echo "    " '{}' " \\" ';' | sort  >> vscope.pri
    echo "" >> vscope.pri

    echo "RESOURCES += \\" >> vscope.pri
    find $DIR -maxdepth 1 -name \*.qrc -exec echo "    " '{}' " \\" ';' | sort  >> vscope.pri
    echo "" >> vscope.pri

    echo "FORMS += \\" >> vscope.pri
    find $DIR -maxdepth 1 -name \*.ui -exec echo "    " '{}' " \\" ';' | sort  >> vscope.pri
    echo "" >> vscope.pri
done

echo "" >> vscope.pri
