// base/enums.h - This file is part of VScope.
// (C) Daniel Wagenaar 2008-1017.
/* VScope is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   VScope is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with VScope.  If not, see <http://www.gnu.org/licenses/>.
*/

// src/base/enums.h - created from 'src/base/enums.xml' by 'tools/enums2c.pl'

// DO NOT EDIT THIS FILE. CHANGES WILL BE LOST.
// (Edit 'src/base/enums.xml' instead, then rerun 'tools/enums2c.pl'.)

#ifndef ENUMS_H
#define ENUMS_H

#define ENUMS_VERSION 20120717

enum PULSETYPE {
  PT_TTL = 0,
  PT_Square = 1,
  PT_Biphasic = 2,
  PT_Ramp = 3,
  PT_Sine = 4,
};

enum SHOWROIS {
  SR_Hidden = 0,
  SR_Centers = 1,
  SR_Outlines = 2,
  SR_IDs = 3,
  SR_Full = 4,
};

enum REFTYPE {
  RT_Analog = 0,
  RT_Digital = 1,
  RT_Frequency = 2,
  RT_Train = 3,
  RT_Pulses = 4,
};

enum DEBLEACH {
  DB_None = 0,
  DB_Linear = 1,
  DB_Quadratic = 2,
};

enum VISUALTYPE {
  VT_Label = 0,
  VT_PageOpen = 1,
  VT_VarOpen = 2,
  VT_VarValue = 3,
  VT_BooleanVar = 4,
  VT_PanelOpen = 5,
  VT_Action = 6,
  VT_Grouped = 7,
  VT_ArrayCtrl = 8,
};

enum CAMERAS {
};

enum AICHAN {
};

enum AOCHAN {
};

enum DIGILINES {
};

enum SHOWWHAT {
  SW_EphysInt = 0,
  SW_EphysExt = 1,
  SW_Stimuli = 2,
  SW_VSDTraces = 3,
  SW_VideoMon = 4,
  SW_CohGraph = 5,
  SW_Welcome = -1,
};

enum FOCUSMODE {
  FM_TwoFull = 0,
  FM_AZoom = 1,
  FM_BZoom = 2,
  FM_TwoZoom = 3,
  FM_Difference = 4,
};

enum VIDEOSTIMTYPE {
  VST_Waves = 0,
  VST_Standing = 1,
  VST_Flicker = 2,
  VST_StaticOn = 3,
  VST_Calibrate = 4,
};

enum VIDEOSTIMTARGET {
  VTGT_All = 0,
  VTGT_Anterior = 1,
  VTGT_Posterior = 2,
};

enum STIMCHS {
};

enum PORTSPEED {
  PS_P0S0 = 0,
  PS_P0S1 = 1,
  PS_P1S0 = 2,
  PS_P1S1 = 3,
};


#endif
